### ISSUE TITLE
Matches & Misses admin screen incorrectly reports Misses as Matches

### ISSUE THREAD

**Issue by campezzi** [MYOB-Technology/http_stub#10] opened 2016-05-04 03:55 UTC
Requests that are not matched to a stubbed endpoint still show up as "Matched" in the Misses/Matches admin screen (`stubs/matches`) with a status of 200. For those requests, the "Match" link points doesn't point anywhere.

Expected behavior: those requests should show a status of 404, indicating they did not match any stubs.

**Comment by campezzi** [comment] 2016-05-04 23:23
This doesn't seem to happen on EVERY miss though - some requests are correctly reported as misses. The one that was incorrectly reported as a match had these characteristics:

- GET request
- URL was matched using a regex
- One specific header was matched using a regex (this was the reason for the miss)

**Comment by dueckes** [comment] 2016-05-05 13:16
@campezzi Any chance you could provide the Configurer to aid with reproducing?

**Comment by dueckes** [comment] 2016-05-31 05:48
@campezzi Are you OK if we close this?  After our last discussion I understood we could not reproduce?

**Comment by dueckes** [comment] 2016-09-05 01:14
Closing due to inactivity - please re-open should you experience this!

**Closed by dueckes** 2016-09-05 01:14 UTC
Labels: question
